import {createRouter,createWebHistory} from 'vue-router'

export default createRouter({
    history:createWebHistory(),
    routes:[
        {
            path:'/home',
            component:()=>import('../views/Home.vue'),
            meta:{
                title:'首页'
            }
        },
        {
            path:'/charts',
            component:()=>import('../views/Charts.vue'),
            meta:{
                title:'房源可视化'
            }
        },
        {
            path:'/map',
            component:()=>import('../views/Map.vue'),
            meta:{
                title:'房源热力图'
            }
        },
        {
            path:'/recommand-a',
            component:()=>import('../views/Recommand-a.vue'),
            meta:{
                title:'协同过滤推荐'
            }
        },
        {
            path:'/recommand-b',
            component:()=>import('../views/Recommand-b.vue'),
            meta:{
                title:'基于内容推荐'
            }
        },
        {
            path:'/login',
            component:()=>import('../views/Login.vue'),
            meta:{
                title:'登录'
            }
        },
        {
            path:'/register',
            component:()=>import('../views/Register.vue'),
            meta:{
                title:'注册'
            }
        },
        {
            path:'/personal',
            component:()=>import('../views/Personal.vue'),
            meta:{
                title:'个人中心'
            }
        },
        {
            path:'/feedback',
            component:()=>import('../views/Feedback.vue'),
            meta:{
                title:'用户反馈'
            }
        },
        {
            path:'/',
            redirect:'/home'
        }
    ],
})